version: '2'

services:
  www_sreda:
    image: php_sreda/php8.1
    
    build: ./.docker
    
    # links:
    #   - mysql
    extra_hosts:
      - "sreda.dev:127.0.0.1"
    ports:
      - 85:80
      #- 443:443
    expose:
      - 9003
    networks:
      - www_sreda_network
    volumes:
      - "./:/var/www/sreda"
    environment:
      PHP_IDE_CONFIG: "serverName=application"
      DB_HOST: host.docker.internal
      VIRTUAL_HOST: "sreda.dev.com"
    container_name: www_sreda_apache_php8_1
    
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: dev_pma
  #   # links:
  #   #   - mysql
  #   environment:
  #     PMA_HOST: host.docker.internal
  #     PMA_PORT: 3306
  #   restart: always
  #   ports:
  #     - 8183:80
    
  # mysql:
  #   container_name: sds2_mysql
  #   image: mysql:5.6
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./.docker/data/mysql:/var/lib/mysql
  #     - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
  #   networks:
  #     - www_network
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "root"
  #     TZ: "Europe/Vilnius"

networks:
  www_sreda_network:
    name: www_sreda_network